#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 <folder_name> <facebook_url> <linkedin_url>"
  exit 1
fi

folder_name="$1"
facebook_url="$2"
linkedin_url="$3"

current_date=$(date "+%Y-%m-%d %H:%M:%S")

# Membuat folder utama dengan nama sesuai dengan argumen pertama
main_folder_name="$folder_name at $current_date"
mkdir -p "$main_folder_name"

# Masuk ke dalam folder utama
cd "$main_folder_name"

# Membuat folder about_me dan subfolder personal dan professional
mkdir -p "about_me/personal"
mkdir -p "about_me/professional"

# Membuat file facebook.txt dan linkedin.txt dengan isi sesuai dengan 
argumen kedua dan ketiga
echo "Facebook URL: $facebook_url" > "about_me/personal/facebook.txt"
echo "LinkedIn URL: $linkedin_url" > "about_me/professional/linkedin.txt"

# Membuat folder my_friends
mkdir -p "my_friends"

# Mengisi file list_of_my_friends.txt dengan data yang sesuai
friends=("Achmad Miftahul - amulum"
         "Achmad Rafiq - achmadrafiq97"
         "Adiststi - adiststi"
         "Agung - agungajin19"
         "Azzahra - al7262"
         "Charisma - fadzrichar"
         "Farida - ulfarida"
         "Garry - garryarielcussoy"
         "Hamdi - hamdiranu"
         "Hedy Gading - Gading09"
         "Ilham - aamfatur"
         "Lelianto - Lelianto"
         "Mohammad - daffa99"
         "Muhammad Fadhil - fabdulkarim"
         "Ofbimon - bimon-alta"
         "Purnama Syafitri - pipitmnr"
         "Setyo - setyoyo07"
         "Wildan - wiflash"
         "Willy - sumarnowilly94"
         "Woka - woka20")

for friend in "${friends[@]}"; do
  echo "$friend" >> "my_friends/list_of_my_friends.txt"
done

# Membuat folder my_system_info
mkdir -p "my_system_info"

# Mengisi file about_this_laptop.txt dengan data yang sesuai
about_this_laptop_info="User: $(whoami)\n$(uname -a)"
echo -e "$about_this_laptop_info" > "my_system_info/about_this_laptop.txt"

# Mengisi file internet_connection.txt dengan hasil ping ke google.com 
sebanyak 3 kali
ping -c 3 google.com > "my_system_info/internet_connection.txt"

echo "Automate script completed successfully."

